services:
  web1:
    build: ./web1
    restart: unless-stopped

  web2:
    build: ./web2
    restart: unless-stopped

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web1
      - web2
    restart: unless-stopped