services:
  site1:
    build: ./site1
    ports:
      - "3000:3000"
    restart: unless-stopped

  site2:
    build: ./site2
    ports:
      - "3001:3001"
    restart: unless-stopped

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - site1
      - site2
    restart: unless-stopped
